repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--strict, src/, tests/, scripts/]
        pass_filenames: false
        additional_dependencies:
          - types-protobuf
          - types-PyYAML
          - grpc-stubs
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.8.3
    hooks:
      - id: pydoclint
        args: [--exclude=src/apme/v1/, src/, tests/, scripts/]
        pass_filenames: false
