apiVersion: v1
kind: Service
metadata:
  name: {{ include "apme.fullname" . }}-engine
  labels:
    {{- include "apme.labels" . | nindent 4 }}
    app.kubernetes.io/component: engine
spec:
  type: ClusterIP
  ports:
    - name: grpc-primary
      port: 50051
      targetPort: 50051
      protocol: TCP
    {{- if .Values.collectionHealth.enabled }}
    - name: grpc-collection-health
      port: 50058
      targetPort: 50058
      protocol: TCP
    {{- end }}
    {{- if .Values.depAudit.enabled }}
    - name: grpc-dep-audit
      port: 50059
      targetPort: 50059
      protocol: TCP
    {{- end }}
  selector:
    {{- include "apme.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: engine
