# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apme.v1 import reporting_pb2 as apme_dot_v1_dot_reporting__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in apme/v1/reporting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportingStub(object):
    """Reporting receives scan/fix events from engine pods (ADR-020).
    The gateway implements this service; engine pods are gRPC clients.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportScanCompleted = channel.unary_unary(
                '/apme.v1.Reporting/ReportScanCompleted',
                request_serializer=apme_dot_v1_dot_reporting__pb2.ScanCompletedEvent.SerializeToString,
                response_deserializer=apme_dot_v1_dot_reporting__pb2.ReportAck.FromString,
                _registered_method=True)
        self.ReportFixCompleted = channel.unary_unary(
                '/apme.v1.Reporting/ReportFixCompleted',
                request_serializer=apme_dot_v1_dot_reporting__pb2.FixCompletedEvent.SerializeToString,
                response_deserializer=apme_dot_v1_dot_reporting__pb2.ReportAck.FromString,
                _registered_method=True)


class ReportingServicer(object):
    """Reporting receives scan/fix events from engine pods (ADR-020).
    The gateway implements this service; engine pods are gRPC clients.
    """

    def ReportScanCompleted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportFixCompleted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportScanCompleted': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportScanCompleted,
                    request_deserializer=apme_dot_v1_dot_reporting__pb2.ScanCompletedEvent.FromString,
                    response_serializer=apme_dot_v1_dot_reporting__pb2.ReportAck.SerializeToString,
            ),
            'ReportFixCompleted': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportFixCompleted,
                    request_deserializer=apme_dot_v1_dot_reporting__pb2.FixCompletedEvent.FromString,
                    response_serializer=apme_dot_v1_dot_reporting__pb2.ReportAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apme.v1.Reporting', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apme.v1.Reporting', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Reporting(object):
    """Reporting receives scan/fix events from engine pods (ADR-020).
    The gateway implements this service; engine pods are gRPC clients.
    """

    @staticmethod
    def ReportScanCompleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.Reporting/ReportScanCompleted',
            apme_dot_v1_dot_reporting__pb2.ScanCompletedEvent.SerializeToString,
            apme_dot_v1_dot_reporting__pb2.ReportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportFixCompleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.Reporting/ReportFixCompleted',
            apme_dot_v1_dot_reporting__pb2.FixCompletedEvent.SerializeToString,
            apme_dot_v1_dot_reporting__pb2.ReportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
